name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERPASSWORD }} 
      - name: Build docker image
        run: docker build -t ambika06101995/nodejs-app .
      - name: Publish docker image to docker hub
        run: docker push ambika06101995/nodejs-app:latest
